version: "3"
services:
  web-scrape:
    build:
      context: .
      dockerfile: Dockerfile
    image: web-scrape
    container_name: web-scrape-con
    environment:
      - NODE_ENV=production
    command: ["npm", "start"]
    network_mode: host
    dns:
    - 8.8.8.8